#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------



#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace Endjin.Selenium.SpecFlowPlugin.Specs
{
    #region Using Directives

    using System.CodeDom;
    using System.Globalization;
    using System.IO;
    using Endjin.Selenium.SpecFlowPlugin;
    using Machine.Specifications;
    using TechTalk.SpecFlow.Generator;
    using TechTalk.SpecFlow.Generator.Configuration;
    using TechTalk.SpecFlow.Parser;
    using TechTalk.SpecFlow.Parser.SyntaxElements;
    using TechTalk.SpecFlow.Utils;

    #endregion

    [Subject(typeof(SeleniumNUnitTestGeneratorProvider))]
    public class when_the_selenium_nunit_test_generator_is_asked_to_generate_tests
    {
        private const string SampleFeatureFile = @"
            @SauceLabConfig
            Feature: Sample feature file for a custom generator provider
            
            Scenario: Simple scenario
				Given there is something
				When I do something
				Then something should happen";

        Establish context = () =>
        {
            var parser = new SpecFlowLangParser(new CultureInfo("en-US"));

            using (var reader = new StringReader(SampleFeatureFile))
            {
                Feature feature = parser.Parse(reader, null);

                var seleniumNUnitTestGeneratorProvider = new SeleniumNUnitTestGeneratorProvider(new CodeDomHelper(CodeDomProviderLanguage.CSharp));

                var codeDomHelper = new CodeDomHelper(CodeDomProviderLanguage.CSharp);

                var converter = new UnitTestFeatureGenerator(seleniumNUnitTestGeneratorProvider, codeDomHelper, new GeneratorConfiguration { AllowRowTests = true, AllowDebugGeneratedFiles = true }, new DecoratorRegistryStub());
                    
                CodeNamespace code = converter.GenerateUnitTestFixture(feature, "TestClassName", "Target.Namespace");
            }
        };

        Because of = () => { };

        It should_ = () => { };
    }
}